#!/bin/sh
set -e

case "$1" in
    remove|purge)
        # Limpiar la caché temporal de imágenes descargadas en /tmp
        if [ -d "/tmp/wallpaper_manager_cache" ]; then
            rm -rf /tmp/wallpaper_manager_cache
        fi
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm llamado con un argumento desconocido \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
