#!/bin/sh
set -e

if dpkg -l | grep -q "^ii  wallpaper-manager "; then
    echo "
    
=========================================================================="
    echo "ATTENTION: 'wallpaper-manager' was detected installed on the system."
    echo "Please uninstall it manually before continuing:"
    echo "sudo apt remove wallpaper-manager"
    echo "=========================================================================="
    echo "
=========================================================================="
    echo "ATENCIÓN: Se detectó 'wallpaper-manager' instalado en el sistema."
    echo "Por favor, desinstálalo manualmente antes de continuar:"
    echo "sudo apt remove wallpaper-manager"
    echo "==========================================================================


"
    exit 1
fi

#DEBHELPER#
